const artworks = [
  {
    title: "La Gardienne des Tournesols",
    category: "portrait",
    image: "CHAMASITE/oeuvre-01.jpeg",
    technique: "Acrylique et effets metalliques sur toile",
    size: "Format vertical",
    year: "2026",
    price: "Sur demande",
    note: "Un portrait solaire, entre regard gris, fleurs vibrantes et envol symbolique.",
  },
  {
    title: "Le Chemin du Berger",
    category: "paysage",
    image: "CHAMASITE/oeuvre-02.jpeg",
    technique: "Acrylique sur toile encadree",
    size: "Format vertical",
    year: "2026",
    price: "Sur demande",
    note: "Une scene marocaine douce, traversee par la lumiere et le mouvement du troupeau.",
  },
  {
    title: "Deux Coeurs au Soleil",
    category: "animalier",
    image: "CHAMASITE/oeuvre-03.jpeg",
    technique: "Acrylique texturee sur toile",
    size: "Petit format",
    year: "2026",
    price: "Sur commande",
    note: "Deux oiseaux rapproches devant un soleil d'or, comme une declaration tranquille.",
  },
  {
    title: "Cimes d'Or et de Brume",
    category: "paysage",
    image: "CHAMASITE/oeuvre-04.jpeg",
    technique: "Acrylique et relief dore sur toile",
    size: "Grand format horizontal",
    year: "2026",
    price: "Sur demande",
    note: "Un paysage montagneux lumineux, entre froid bleute et sommets dores.",
  },
  {
    title: "Le Roi du Silence",
    category: "animalier",
    image: "CHAMASITE/oeuvre-05.jpeg",
    technique: "Acrylique sur toile encadree",
    size: "Format vertical",
    year: "2026",
    price: "Sur demande",
    note: "Un lion frontal, dense et majestueux, peint sur fond noir.",
  },
  {
    title: "Racines du Maroc",
    category: "commande",
    image: "CHAMASITE/oeuvre-06.jpeg",
    technique: "Acrylique et texture sur toile",
    size: "Format carre",
    year: "2026",
    price: "Commande personnalisee",
    note: "Une composition rouge et verte, hommage affectif a la transmission.",
  },
  {
    title: "Le Souffle Bleu",
    category: "animalier",
    image: "CHAMASITE/oeuvre-07.jpeg",
    technique: "Acrylique sur toile encadree",
    size: "Format horizontal",
    year: "2026",
    price: "Sur demande",
    note: "Une tortue marine avance dans un monde bleu profond, calme et vivant.",
  },
  {
    title: "Majeste Interieure",
    category: "animalier",
    image: "CHAMASITE/oeuvre-08.jpeg",
    technique: "Acrylique sur toile",
    size: "Format vertical",
    year: "2026",
    price: "Sur demande",
    note: "Un lion clair et intense, compose comme une icone de force tranquille.",
  },
  {
    title: "Route vers les Cimes",
    category: "commande",
    image: "CHAMASITE/oeuvre-09.jpeg",
    technique: "Acrylique sur toile",
    size: "Format vertical",
    year: "2026",
    price: "Commande personnalisee",
    note: "Une commande automobile qui mele passion mecanique, paysage et horizon.",
  },
  {
    title: "Mourra wa Rahma",
    category: "commande",
    image: "CHAMASITE/oeuvre-10.jpeg",
    technique: "Calligraphie, relief et acrylique sur toile",
    size: "Format carre",
    year: "2026",
    price: "Sur commande",
    note: "Une piece calligraphique en relief, entre matiere ancienne et douceur florale.",
  },
  {
    title: "Cinema des Reves Electriques",
    category: "imaginaire",
    image: "CHAMASITE/oeuvre-11.jpeg",
    technique: "Acrylique sur toile",
    size: "Format horizontal",
    year: "2026",
    price: "Sur demande",
    note: "Une salle de cinema vide ou l'imaginaire prend l'ecran et traverse les sieges.",
  },
  {
    title: "Vaisseau du Crepuscule",
    category: "paysage",
    image: "CHAMASITE/oeuvre-12.jpeg",
    technique: "Acrylique sur toile encadree",
    size: "Format vertical",
    year: "2026",
    price: "Sur demande",
    note: "Un navire de face, porte par une mer vive sous un ciel flamboyant.",
  },
  {
    title: "L'Astronaute aux Tournesols",
    category: "imaginaire",
    image: "CHAMASITE/oeuvre-15.jpeg",
    technique: "Acrylique sur toile encadree",
    size: "Grand format horizontal",
    year: "2026",
    price: "Sur demande",
    note: "Un astronaute pose dans un champ de tournesols, entre science-fiction et reve terrestre.",
  },
  {
    title: "Regards a Rayures",
    category: "portrait",
    image: "CHAMASITE/oeuvre-16.jpeg",
    technique: "Acrylique graphique sur toile",
    size: "Format horizontal",
    year: "2026",
    price: "Sur demande",
    note: "Une figure pop aux lunettes rouges, fragmentee par des bandes de couleur.",
  },
];

const categoryLabel = {
  portrait: "Portrait",
  animalier: "Animalier",
  paysage: "Paysage",
  imaginaire: "Imaginaire",
  commande: "Commande personnalisee",
};

